# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
