# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0003_auto_20170813_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Nick', max_length=128),
            preserve_default=False,
        ),
    ]
