# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0004_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Anon', max_length=128),
        ),
    ]
